version: '3'
services:
  app:
    image: app
    container_name: simple_chat_backend_app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    # To check logs on the server without accessing the container
    volumes:
      - ./prodlog:/app/Logs
    depends_on:
      - db
  db:
    container_name: simple_chat_backend_db_prod
    build: ./postgres
    env_file: ./postgres/.env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"
volumes:
  pgdata: